### ISSUE TITLE
SHOWCASE: OpenMoji.org

### ISSUE THREAD

**Issue by stephanbogner** [withastro/astro.build#104]
### Website title

OpenMoji.org

### Short description and preview image

Open source emojis for designers, developers and everyone else!

<img width="1244" alt="website-preview" src="https://user-images.githubusercontent.com/7897006/166101658-9e691f33-0ee3-4a6d-bf19-4b19de27498f.png">

### Public website URL

https://openmoji.org/

**Comment by delucis** [comment]
Really nice!

Adding the site repo here in case anyone’s interested in taking a look: https://github.com/hfg-gmuend/openmoji.org
