### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by JuanPabloDiaz** [withastro/astro.build#1043]
### Astro Info

```block
astro build themes website
```

### Describe the Bug

In the **astro build themes** page, all the content from the author **flamrdevs** is not found in GitHub

in other words, the get started button is taking you to a not found page in GitHubfor this two projects
- https://astro.build/themes/details/astrolinkt
- https://astro.build/themes/details/astrovehnt/

the user **flamrdevs** cant be found on GitHub

### What's the expected result?

take you to the repos

### Link to Minimal Reproducible Example

https://github.com/flamrdevs/astrolinkt

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
cc @ElianCodes

**Comment by ElianCodes** [comment]
I'm taking a look!

**Comment by ElianCodes** [comment]
Hey @JuanPabloDiaz! Thanks for opening an issue on this. It seems like the original creator of these themes has deleted their GitHub profile, which is why the links don't work.

We'll remove the themes from the catalog.

Thanks for taking the time to open an issue!
