### ISSUE TITLE
THEME:AstroBoy

### ISSUE THREAD

**Issue by mesinkasir** [withastro/astro.build#106]
### Theme title

Astro Boy

### Short description and preview image

Astro boy starter blog template for build modern blog with astro build.  features : simple blog, auto SEO from astro, cover image blog, post article, markdown support.

![astrowebtemplate](https://user-images.githubusercontent.com/52827888/166120483-66861e87-981c-49d0-b2d9-e960dd22ab82.jpg)
 

### Public repository URL

https://github.com/mesinkasir/astro-website-template-themes-source-code-download

### Live demo URL

https://astroman.vercel.app/

**Comment by tony-sull** [comment]
Sorry for the dleay here @mesinkasir!  The description text will be shown on the card when added to the Themes page, would you mind updating the PR with a little more detail that highlights what devs will find when they clone the theme?

**Comment by mesinkasir** [comment]
> Sorry for the delay here @mesinkasir! The description text will be shown on the card when added to the Themes page, would you mind updating the PR with a little more detail that highlights what devs will find when they clone the theme?

Oh oke..
