### ISSUE TITLE
[Visual bug] "Integrations" link text in header under "Resources" submenu breaks on new line

### ISSUE THREAD

**Issue by edburtnieks** [withastro/astro.build#1069]
## Reproduce

1. Visit https://astro.build on screens >= 1024px
2. Open "Resources" submenu

**Repeatability**: 100%
**Operating systems and browsers**:
- Reproducible on Linux - Chrome 123, Firefox 124
- **Not** reproducible on Windows - Chrome 123, Firefox 124

## Expected result

"Integrations" link text in header under "Resources" submenu is in one line

![image](https://github.com/withastro/astro.build/assets/85392357/59d354b5-aac2-46fe-b223-6df0d256b146)

## Actual result

"Integrations" link text in header under "Resources" submenu breaks on new line

![image](https://github.com/withastro/astro.build/assets/85392357/08f8163f-b00d-40ff-8614-b5de587297d7)

## Potential solution

Adding `whitespace-nowrap` tailwind class to links inside the "Resources" submenu

See: https://github.com/withastro/astro.build/blob/20d174e1a3c180558f97b3a64bcd805d7865f3c1/src/components/ResourcesMenu.astro#L49

**Comment by ElianCodes** [comment]
Weird, this doesn't seem to happen on any of my machines. The viewport changes to the mobile layout before the line starts to break.

**Comment by edburtnieks** [comment]
Yeah, it only happens on my Linux machine

**Comment by delucis** [comment]
I believe this should now be fixed as this menu was tweaked slightly. Feel free to re-report if not!
