### ISSUE TITLE
THEME:Cuteblog

### ISSUE THREAD

**Issue by mesinkasir** [withastro/astro.build#107]
### Theme title

Cuteblog for astro blogger

### Short description and preview image

Blog with simple and unique design to create blog site using astro, features cute blog with card design ,markdown ready , and blog post cover image .

![new free website template download](https://user-images.githubusercontent.com/52827888/166120570-1ce300a4-b143-407d-b8ac-ac0ade192d52.jpg)

### Public repository URL

https://github.com/mesinkasir/cute-blog

### Live demo URL

https://cuteblog.netlify.app/

**Comment by tony-sull** [comment]
Sorry for the delay here @mesinkasir!  The description text will be shown on the card when added to the Themes page, would you mind updating the PR with a little more detail that highlights what devs will find when they clone the theme?
