### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jamesli2021** [withastro/astro.build#1126]
Nice, I have seen that the site has been revamped.
Suggestions:

- The current font doesn't look good; consider reverting to the previous font.
- Remove the "Real-World Core Web Vitals" and chart, as it's an ineffective comparison on a marketing site in terms of performance. In fact, no site ever show that and it should be coming from the tools that can provide real measurements which every projects evolve over time.
- The home page layout appears cluttered and poorly redesigned.
- In the "Zero Lock-in" section, I clicked on the UI framework icons but received no useful feedback. What am I supposed to see?
- It's WordPress with upper case P.

**Comment by JusticeMatthew** [comment]
I wouldn't say the new home layout is poorly redesigned however I do feel things are a bit cramped on the y axis

I think a bit more padding between content and titles as well as between each section might be in order

**Comment by jamesli2021** [comment]
Most people using WordPress sites aren't developers (e.g., WordPress users); thus, comparing them to developers working on their sites using Astro could be unfair, especially if WordPress users employ it for learning purposes. You knew that Evan You mentioned the large part of Nuxt 2 are in used.

**Comment by delucis** [comment]
Thanks for the feedback!
