### ISSUE TITLE
Blurry Wordpress logo icon

### ISSUE THREAD

**Issue by evadecker** [withastro/astro.build#1138]
![image](https://github.com/withastro/astro.build/assets/4117920/c2958672-3eec-4f6f-8269-13fe8e3e3b24)

On iOS I'm getting a blurry Wordpress icon in the performance comparison list. Seems like maybe it's using a .png while the other icons are .svg, but I'm not at a computer to check right now.

**Comment by evadecker** [comment]
Yup, still seeing it on iOS Safari

![image](https://github.com/withastro/astro.build/assets/4117920/f9e08e23-ead0-483a-a898-3749db3f4047)

**Comment by delucis** [comment]
Thanks! I should probably have tried looking inside the SVG 😁 

https://github.com/withastro/astro.build/blob/eec74745cf0ad281469e3a607af624dc5a76e9c5/public/assets/web-vitals/wordpress-logo.svg#L1-L9

It’s a PNG-in-SVG! Not sure why… Pretty sure we could swap it out for a proper one.
