### ISSUE TITLE
INTEGRATION: add astro-github-component icon

### ISSUE THREAD

**Issue by vaporvee** [withastro/astro.build#1159]
### NPM package name

astro-github-component

### Short description (if different than package.json) and icon

Hello could you take this as icon please?

![astro-github-component](https://github.com/withastro/astro.build/assets/80621863/4e1a9841-cc9e-4707-8cd8-26acfcdb69fc)

### Homepage URL (if different than package.json)

https://github.com/vaporvee/astro-github-component

**Comment by pascal-brand38** [comment]
Hello,
Do you have any square icon, either as svg or 64x64 png file?
Thanks a lot,
Pascal.

**Comment by delucis** [comment]
As we haven’t had any response on this one, I think we can close it now. Thanks again everyone!
