### ISSUE TITLE
INTEGRATION: @voxgig/podw-astro

### ISSUE THREAD

**Issue by lmscunha** [withastro/astro.build#1169]
### NPM package name

@voxgig/podw-astro

### Short description (if different than package.json) and icon

![voxgig-logo](https://github.com/withastro/astro.build/assets/65237061/23708dd1-3535-45f9-b7f6-63441b18436d)

### Homepage URL (if different than package.json)

https://github.com/voxgig/podmind-plugins

**Comment by pascal-brand38** [comment]
@lmscunha Thanks a lot.
I have one question before integrating it in astro.build: the homepage url you provided (https://github.com/voxgig/podmind-plugins) does not provide relevant information (empty repo).

Should we use https://www.npmjs.com/package/@voxgig/podw-astro  as the homepage url instead as it really describes how to install this astro integration?

Thanks for your help.

**Comment by lmscunha** [comment]
Agree, please do. Thank you for pointing that out.  👍🏾
