### ISSUE TITLE
[GitHub OAuth Error on Astro Dev Portal] Unable to login to submit theme

### ISSUE THREAD

**Issue by vinitshahdeo** [withastro/astro.build#1178]
I'm encountering an issue with logging into the [Astro Dev Portal](https://portal.astro.build/login) using GitHub to submit my theme. It appears that GitHub OAuth is failing with the following error:

```
https://portal.astro.build/login?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch
```

> I have developed my portfolio using Astro (live at [vinitshahdeo.com](https://vinitshahdeo.com)) and am eager to submit it as a free and [open-source theme](https://github.com/vinitshahdeo/portfolio). Could you please assist me in resolving this login issue so that I can proceed with the submission?

**Comment by delucis** [comment]
Thanks for the report @vinitshahdeo! I just redeployed the dev portal. Would you mind trying to log in again?

**Comment by vinitshahdeo** [comment]
Thanks for the quick resolution. I was able to submit the theme now: https://portal.astro.build/themes/stellar-astro-dev-portfolio/

Can you please help me with the review process?

**Comment by delucis** [comment]
Someone will take a look soon! Thanks for checking 🙌
