### ISSUE TITLE
Blog RSS feed unstable

### ISSUE THREAD

**Issue by inwardmovement** [withastro/astro.build#121]
Hi,

My feed reader is each time displaying every article of the blog, whereas it should be displaying only the new ones.
Before suspecting my feed reader, I'd like to know: the blog RSS feed (`astro.build/rss.xml`) seems to be regenerating from scratch at each website update (maybe a problem with articles dates?). Can you confirm? A fix would be appreciated 😄

**Comment by tony-sull** [comment]
Fixed with PR #123  🎉
