### ISSUE TITLE
fix Spelling "talwind" to "tailwind"

### ISSUE THREAD

**Issue by amanr-dev** [withastro/astro.build#1239]
At ``https://astro.build/themes/details/aubergine/``, I noticed a small spelling mistake in the portfolio template section. The word "Tailwind" is misspelled as "Talwind."

### screenshot:
![Screenshot 2024-08-30 103743](https://github.com/user-attachments/assets/33ad0f2f-4bc1-4080-b967-87b91d6ccd0c)

**Comment by delucis** [comment]
Thanks for the report — just fixed this 🙌
