### ISSUE TITLE
THEME: Odyssey Theme

### ISSUE THREAD

**Issue by jaydanurwin** [withastro/astro.build#129]
### Theme title

Odyssey Theme

### Short description and preview image

A modern, full-featured theme for a business or startup marketing site.

![odyssey-theme netlify app_](https://user-images.githubusercontent.com/42281662/169659386-80a3151c-1b13-43af-907d-57d2ddfc81ed.png)

### Public repository URL

https://github.com/littlesticksdev/odyssey-theme

### Live demo URL

https://odyssey-theme.littlesticks.dev/

**Comment by gretchunkim** [comment]
The live demo url no longer works. The latest url is https://odyssey-theme.sapling.supply/. 

Can we please get the link updated again?

**Comment by delucis** [comment]
Thanks for the heads up @gretchunkim — should be updated now 🙌
