### ISSUE TITLE
INTEGRATION: astroid

### ISSUE THREAD

**Issue by xisli** [withastro/astro.build#164]
### NPM package name

astroid

### Short description (if different than package.json) and icon

![astroid](https://user-images.githubusercontent.com/40587137/175265515-517e6263-521c-4e45-8fcf-2fdadc6f326d.png)

A router for inspired by nextjs that includes a link component, prefetching, query params and a router function.

### Homepage URL (if different than package.json)

https://github.com/xisli/astroid

**Comment by tony-sull** [comment]
@xisli Very cool!  Looks like the package on NPM is missing the keywords used by our integrations page

[See here](https://docs.astro.build/en/guides/publish-to-npm/#packagejson-data) for docs on exactly what details we scrub from the NPM listing.  Ping me here once the updated package.json is published to NPM and we'll make sure the custom icon is added on our end :+1:

**Comment by xisli** [comment]
@tony-sull  done.

**Comment by tony-sull** [comment]
Perfect, thanks!  I'll have this icon updated tomorrow!
