### ISSUE TITLE
THEME: Minimal starter with Tailwind CSS

### ISSUE THREAD

**Issue by michael-andreuzza** [withastro/astro.build#165]
### Theme title

Minimal starter with Tailwind CSS

### Short description and preview image

An extremely minimal and dark starter styled wit Tailwind CSS

### Public repository URL

https://github.com/UnwrappedDesign/astro-build-tailwind-starter

### Live demo URL

https://main--astro-build-tailwind-starter.netlify.app/

**Comment by tony-sull** [comment]
Thanks for submitting this, @michael-andreuzza!  Would you mind adding the screenshot you'd like to show up on the astro.build Themes page?

**Comment by michael-andreuzza** [comment]
Hey, you are very welcome.

Sure, does this one works?

/Mike

![astroTemplate](https://user-images.githubusercontent.com/34077176/177380175-79ddfee7-be5f-4179-b7fa-9bbe095bd996.png)
!

**Comment by tony-sull** [comment]
That'll work, thanks!  I'll get this added in tomorrow!

**Comment by michael-andreuzza** [comment]
Superb, thank you so much Tony, hope someone finds it useful. 
I will contribute with more templates in the future.

**Comment by michael-andreuzza** [comment]
Hey Tony, it looks like I gave you the wrong link for any reason. The "main--" part shouldn't be in the domain name.

Sorry for the inconvenience.

/Mike
