### ISSUE TITLE
Images without dimensions cause layout shift

### ISSUE THREAD

**Issue by TimonVS** [withastro/astro.build#172]
You may already be aware of this, but images without dimensions can cause layout shift, which is the case for the blog articles for instance:

https://user-images.githubusercontent.com/876666/176473160-8c00bf80-9543-4bc7-b299-172916c59eb4.mp4

This can be fixed by adding image dimensions to the `img` elements: https://web.dev/optimize-cls#images-without-dimensions. I'd be happy to help out if I can :)

**Comment by tony-sull** [comment]
This will be fixed up next week!  We just released the `@astrojs/image` integration for exactly this kind of use case, can't wait to dogfood it a bit on our production site 🎉

**Comment by tony-sull** [comment]
The freshly rebuilt astro.build site now uses the `@astrojs/image` integration and always includes width/height on images to avoid layout shift 🎉
