### ISSUE TITLE
Easter egg fails to load due to adblocking plugins

### ISSUE THREAD

**Issue by Princesseuh** [withastro/astro.build#18]
## Problem

A very commonly used filter list used by adblocking plugins and browsers with integrated adblocking block files named `analytics.js` by default, no matter their content. The problem this causes is that the easter egg on the website does not work on many configurations, again due to the naming of the file. The filter is really common and enabled by default for most plugins so I suspect this affect a bunch of users

## Potential solutions

While the easter egg working isn't the biggest priority (or is it?), it'd be great if we could change the name of the file to something else in order to avoid it being blocked by accident for users using adblock. 

Now, since the funny name is part of the joke, we should replace this with another funny name. Perhaps something like `hugeamountof.js` or something similar in order to stay in theme with Astro?

**Comment by boehs** [comment]
> Now, since the funny name is part of the joke, we should replace this with another funny name. Perhaps something like `hugeamountof.js` or something similar in order to stay in theme with Astro?

I propose `jquery.min.js`

**Comment by FredKSchott** [comment]
fixed!
