### ISSUE TITLE
`[object AsyncGenerator][object AsyncGenerator]` on the website

### ISSUE THREAD

**Issue by X7md** [withastro/astro.build#185]
![25085F52-9816-4880-930E-99CA1563C910](https://user-images.githubusercontent.com/54203033/177552319-71163cd6-bead-48e7-8ab6-7a50d20d5d22.png)

Previewed on Safari iOS + Chrome Android same results

**Comment by delucis** [comment]
Fixed in #187 — thanks @X7md!
