### ISSUE TITLE
INTEGRATION: avatar for 'astro-robots-txt'

### ISSUE THREAD

**Issue by alextim** [withastro/astro.build#207]
### NPM package name

astro-robots-txt

### Short description (if different than package.json) and icon

![robot](https://user-images.githubusercontent.com/6442224/180405769-51a91e59-6a1f-4c8f-affe-90d24574e42f.svg)

### Homepage URL (if different than package.json)

https://github.com/alextim/astro-lib/tree/main/packages/astro-robots-txt#readme

**Comment by tony-sull** [comment]
@alextim looks like there may be an issue with the SVG file, mind taking a quick look?  I took a quick look at the SVG source but nothing jumped out at me

When opening the SVG directly [here](https://user-images.githubusercontent.com/6442224/180405769-51a91e59-6a1f-4c8f-affe-90d24574e42f.svg) the colors are missing, when running locally it's closer but I get the image below

<img width="511" alt="Screen Shot 2022-07-26 at 10 03 36 AM" src="https://user-images.githubusercontent.com/15836226/181041688-f0b18061-7575-4701-b02c-0a8ed37f1c4f.png">

**Comment by tony-sull** [comment]
Closing this out as stale but happy to update the icon if you open a new issue with an updated SVG or PNG 👍
