### ISSUE TITLE
The animated background in the islands section might be problematic

### ISSUE THREAD

**Issue by orenelbaum** [withastro/astro.build#231]
Looking at the background reminded me of this tweet where Jamie Kyle talks about how a similar background gave him motion sickness
https://twitter.com/buildsghost/status/1502042182017900547
He's explaining it more in depth there and he's also saying that it shouldn't be done even if reduced motion isn't turned on.
Other than that I have to say the new website looks great, awesome work.

**Comment by delucis** [comment]
Thanks for sharing the thread @orenelbaum! We do respect reduced motion, placing this behind a `prefers-reduced-motion: no-preference` media query, and intentionally chose to not make this a long-running animation (which Jamie also recommends in that thread).

Maybe that’s not enough though and we could look into a static image background instead.

**Comment by orenelbaum** [comment]
Well I just wanted to bring it to your attention, you guys can decide if it's accessible enough or not. Personally, the animation is the only part I didn't like about this design anyway, it looks nice but I find it kind of distracting and a bit over the top. But that's very much a personal taste thing so really up to you guys and what you think is a accessible enough.

**Comment by tony-sull** [comment]
@orenelbaum thanks for raising this, that's definitely a tricky one to keep an eye on!  The animations are disabled for users with reduced motion preferences enabled so we should be good here, but we'll absolutely keep an eye out for any users experiencing accessibility issues even with those preferences honored :+1:
