### ISSUE TITLE
SHOWCASE: Jamstacker Studio

### ISSUE THREAD

**Issue by michael-andreuzza** [withastro/astro.build#239]
### Website title

Jamstacker Studio

### Short description and preview image

Premium web design & development for startups with fixed timeline & price.

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/34077176/184542817-9fb1141b-8114-486a-8ab8-bcef9bb81b7f.png">

### Public website URL

https://jamstacker.studio/

**Comment by tony-sull** [comment]
Closing as a duplicate of #238 👍
