### ISSUE TITLE
THEME: Art Theme

### ISSUE THREAD

**Issue by npmrun** [withastro/astro.build#270]
### Theme title

Art Theme

### Short description and preview image

Beautiful blog template with Astro

![2022-09-01_21-22](https://user-images.githubusercontent.com/62639956/187924501-f9f77ab1-a508-4eca-9e4a-edea683a4560.png)

### Public repository URL

https://github.com/npmrun/art-theme

### Live demo URL

https://art-theme.netlify.app

**Comment by delucis** [comment]
Thanks @npmrun! Just added this 🙌
