### ISSUE TITLE
Building the new website

### ISSUE THREAD

**Issue by swift502** [withastro/astro.build#271]
Hi,

I noticed that cloning this repository and building it builds the old version of astro.build.

![image](https://user-images.githubusercontent.com/24359130/188109771-9ee368a9-4794-4f60-a9bb-de481e8db26a.png)

The data for showcased projects and themes also doesn't seem to match what's actually live.

Is it possible to build the new version?
Is it not in this repository? Is it in a different branch or repo?

Thanks!

**Comment by delucis** [comment]
Hi @swift502! The new website is in a private repository currently — I think there were concerns about making that public in case any of it was using proprietary components from Tailwind UI. /cc @FredKSchott to confirm

**Comment by swift502** [comment]
Ok, it's no big deal. Just a bit confusing.

Maybe a readme mention would be appropriate if it's long term.

**Comment by tony-sull** [comment]
Excited to say the new website source has been migrated here, back to business as usual deploying to astro.build from this public repo 🎉
