### ISSUE TITLE
https://pauliescanlon.github.io/

### ISSUE THREAD

**Issue by PaulieScanlon** [withastro/astro.build#280]
### Website title

A dashboard for GitHub Events

### Short description and preview image

This site is built using [Astro](https://astro.build/) and displays both static and dynamic GitHub user and repository events data.
Data is sourced at both build and run-time using Cross Origin [Gatsby Functions](https://www.gatsbyjs.com/products/cloud/functions/) provided by [Paulie API](https://paulieapi.gatsbyjs.io/)

### Public website URL

https://pauliescanlon.github.io/

**Comment by tony-sull** [comment]
@PaulieScanlon oh that's very cool!  I think this is only the second dashboard project I've seen built with Astro, great to see an example using client-side data loading!

Would you mind updating the issue with the image you want us to use in our Showcase?

**Comment by PaulieScanlon** [comment]
Hey @tony-sull, what's the issue with the image? Happy to re-supply one if needed.

**Comment by tony-sull** [comment]
Looks like I completely missed the image in the source repo, sorry about that!  Just merged this in so the showcase should update in a few minutes 🚀
