### ISSUE TITLE
SHOWCASE: Mocked-API

### ISSUE THREAD

**Issue by ageddesi** [withastro/astro.build#284]
### Website title

Mocked-API

### Short description and preview image

A set of FREE Api's that allow you to fill your application with mocked data

### Public website URL

https://mocked-api.dev/

**Comment by tony-sull** [comment]
@ageddesi love the design!  Would you mind updating this issue with the preview image you want us to use in our Showcase?

**Comment by tony-sull** [comment]
That's perfect, thanks!  I just merged this in so the Showcase should update in a few minutes :rocket:
