### ISSUE TITLE
SHOWCASE: miduconf - Conferencia de programación y desarrollo.

### ISSUE THREAD

**Issue by pheralb** [withastro/astro.build#289]
### Website title

miduConf - Conferencia de programación y desarrollo.

### Short description and preview image

- 💖 Website created by [midudev](https://midu.dev/).
- ⚒️ Built with Astro + Preact + TailwindCSS.
- 🚀 Deployed on Netlify.

<img src="https://i.ibb.co/4YF1dbk/miduconf.png" />

### Public website URL

https://miduconf.com/

**Comment by delucis** [comment]
Thanks for this @pheralb! Just added this to the showcase 🙌

**Comment by pheralb** [comment]
Thanks 💖💖🥳🥳
