### ISSUE TITLE
SHOWCASE: hideoo.dev

### ISSUE THREAD

**Issue by HiDeoo** [withastro/astro.build#290]
### Website title

HiDeoo

### Short description and preview image

My personal Open Source Portfolio.

*I needed a small project to play with Astro, the DX was pretty amazing, thanks for all the hard work.*

![preview image](https://user-images.githubusercontent.com/494699/189947355-fd957081-3ed4-46df-a6b1-c42233ce4b93.png)

### Public website URL

https://hideoo.dev

**Comment by akshatcoder-hash** [comment]
Hey @HiDeoo @natemoo-re I would love to work on this issue. Kindly assign this to me.
