### ISSUE TITLE
SHOWCASE: add personal website

### ISSUE THREAD

**Issue by kevinzunigacuellar** [withastro/astro.build#292]
### Website title

Kevin Zuniga Cuellar

### Short description and preview image

Personal portfolio and developer journal 
![www kevinzunigacuellar com](https://user-images.githubusercontent.com/46791833/190274144-d294df1c-bb73-49a3-ac8f-9d8bf61d2080.png)

### Public website URL

https://www.kevinzunigacuellar.com/

**Comment by akshatcoder-hash** [comment]
Hey @kevinzunigacuellar  @natemoo-re I would love to work on this issue. Kindly assign this to me.

**Comment by tony-sull** [comment]
Hey @akshatcoder-hash!  We *just* finished the chore of migrating over the new astro.build website design back to this public repo (it was a private repo we worked in before the 1.0 release)

I'm going to tackle the batch of submissions today just to double check that the first PR after the migration doesn't run into any issues, but I'd be happy to send submissions your way in the future if you're interested in helping out on the showcase and themes pages!
