### ISSUE TITLE
THEME UPDATE: Odyssey Theme (new preview image)

### ISSUE THREAD

**Issue by jaydanurwin** [withastro/astro.build#293]
### Theme title

Odyssey Theme

### Short description and preview image

![theme-preview](https://user-images.githubusercontent.com/42281662/190690701-84cb482b-a322-4be5-9841-caa78881bda4.png)

Hi there, I just wanted to push an updated preview image to my existing theme, Odyssey Theme. Thank you!

### Public repository URL

https://github.com/littlesticks/odyssey-theme

### Live demo URL

https://odyssey-theme.littlesticks.dev/

**Comment by tony-sull** [comment]
No problem I'll update that today, that's a beautiful preview image!
