### ISSUE TITLE
SHOWCASE: Barnabas Kendall

### ISSUE THREAD

**Issue by Barnabas** [withastro/astro.build#297]
### Website title

Barnabas Kendall

### Short description and preview image

![barnabas me](https://user-images.githubusercontent.com/90811/191377694-f6ed0e81-caa0-4320-a36c-ebb873f5c279.png)

### Public website URL

https://barnabas.me/

**Comment by akshatcoder-hash** [comment]
Hey @Barnabas  @natemoo-re I would love to work on this issue. Kindly assign this to me.
