### ISSUE TITLE
SHOWCASE: Stylessh - Portfolios

### ISSUE THREAD

**Issue by stylessh** [withastro/astro.build#299]
### Website title

Stylessh - Portfolios

### Short description and preview image

Hey There! I'm Alan Daniel. I'm a Creative Web Developer and Guitarist. I migrated my website from nextjs to astro, and it is real fast!

![ss](https://user-images.githubusercontent.com/45767683/191822231-7035f05d-20e9-41e8-af9c-a593f408895d.png)

### Public website URL

https://stylessh-v2.vercel.app/

**Comment by akshatcoder-hash** [comment]
Hey @stylessh  @natemoo-re I would love to work on this issue. Kindly assign this to me.
