### ISSUE TITLE
SHOWCASE: jamstacker

### ISSUE THREAD

**Issue by michael-andreuzza** [withastro/astro.build#304]
### Website title

jamstacker

### Short description and preview image

Hey, I didn't knew how to approach to remove a project from the showcase.
I have closed the studio on the link:
-   jamstacker.studio

In case you guys don't want dead links, in your site and rather to remove it, this is the screenshot
![image](https://user-images.githubusercontent.com/34077176/192222677-0bda06a5-628f-412f-b8ca-a8528bba4df5.png)

Is not live anymore

### Public website URL

jamstacker.studio

**Comment by tony-sull** [comment]
Thanks for letting us know!  I'll remove it from the showcase today :+1:

**Comment by michael-andreuzza** [comment]
you welcome, have a great day :-)
