### ISSUE TITLE
Bug: Thumbnail lazy-loading seems broken in Themes browser

### ISSUE THREAD

**Issue by swift502** [withastro/astro.build#327]
**Setup:**
Windows 10
Chrome 106.0.5249.91
Tested on 1080p and 1440p screens

**Issue:**
Is it just me, or are the right most thumbnails in the themes browser blank? https://astro.build/themes/other/
(Make sure to de-cache the thumbnails using a Ctrl+F5 reload)

![image](https://user-images.githubusercontent.com/24359130/193634927-a2b96fc9-c9bf-439e-9ae0-f7990fec6e27.png)

Observations:
- Zooming the webpage to 125% loads the images
- Loading the page at other than 100% zoom breaks the thumbnails in slightly different ways

**Comment by swift502** [comment]
@tony-sull Now it's better! Now it displays correctly at 100%. So maybe that's good enough?

But still has trouble with different zoom sizes.

- 1920x1080 screen
- 75% Zoom
- Ctrl + F5

The second row fails to load. Here's a full-screen capture.

![image](https://user-images.githubusercontent.com/24359130/195392105-256bd663-29da-4891-a52c-ff3d7fd545db.png)

**Comment by tony-sull** [comment]
Very strange, thanks for digging into the extra details here!  I'm pretty sure we're just using browser-native lazy loading here, it almost seems like the browser isn't picking up what images are visible on screen?

Not sure if that's something we can fix on our end but I'll see if I can find anything!  Maybe there's a lazy loading threshold we can set, or it could be getting a bit confused by the DOM layout we use for those cards 🤔

**Comment by delucis** [comment]
We’re just using the `loading="lazy"` HTML attribute, so if anything this feels like a browser bug.

**Comment by tony-sull** [comment]
> We’re just using the loading="lazy" HTML attribute, so if anything this feels like a browser bug.

+1, was hoping there was a workaround that forces browsers to reliably lazy load when zoomed in/out but every browser handles this differently (read: it's buggy 🐛 )
