### ISSUE TITLE
Portrolio Website

### ISSUE THREAD

**Issue by sukhop** [withastro/astro.build#331]
### Website title

SukhOP Portfolio

### Short description and preview image

I am a 20 year old self-taught Graphic Designer & Front-End Web Developer, and now I am a final-year student pursuing a degree in Computer Science here in India. I am proficient in frontend development and graphic designing. Likewise, I have 5 years of experience in Graphic Designing & 2 years of experience in Front-End Development. I have built and maintained many websites for clients.

### Public website URL

https://sukhop.netlify.app/

**Comment by tony-sull** [comment]
Hey @sukhop, really nice design on your portfolio!  Would you mind adding a 16:9 screenshot here that you would like us to use in our showcase site?

**Comment by sukhop** [comment]
sir here is the thumbnail for my submission.

**Comment by sukhop** [comment]
![Uploading sukhop_portfolio_thumbnail.png…]()
