### ISSUE TITLE
SHOWCASE: Hung Duong Quang

### ISSUE THREAD

**Issue by qhungg289** [withastro/astro.build#390]
### Website title

Hung Duong Quang

### Short description and preview image

![image](https://user-images.githubusercontent.com/42641045/200126827-b3a91e3a-449c-4780-92fc-967156cd42e4.png)
Hung's Personal Website

### Public website URL

https://qhungg289.github.io/

**Comment by tony-sull** [comment]
@qhungg289 I'm getting a 404 on the Vercel deployment, reopening for now but ping me here when it's back up and we'll get the site added to our showcase 🚀

**Comment by qhungg289** [comment]
@tony-sull Sorry, I moved the deployment to GH Pages and forgot to edit the issue. Here's the new public website URL: https://qhungg289.github.io/
