### ISSUE TITLE
SHOWCASE: Michael Andreuzza

### ISSUE THREAD

**Issue by michael-andreuzza** [withastro/astro.build#414]
### Website title

Michael Andreuzza

### Short description and preview image

Hey guys, just wanted to let you know I have moved and cloes 3 of my projects to other domains and you are gogin to have dead on links on the showcase.

- acclivity.unwrapped.desgin
- monoqrom.unwrapped.design
- brutalist.one

This three do not exist anymore, so for my part you can remove it.

Sorry for the inconvenience and have a great day!

/Mike

### Public website URL

unwrapped.design

**Comment by tony-sull** [comment]
Removing them now, thanks for the heads-up!  Also a great reminder for the task that keeps falling off my list of automating a dead link checker for our themes & showcase 😅

**Comment by michael-andreuzza** [comment]
> Removing them now, thanks for the heads-up! Also a great reminder for the task that keeps falling off my list of automating a dead link checker for our themes & showcase 😅

Hey Tony, you are very welcome Tony! I should have thought twice to open a PR before switching them to Unwrapped.design

I guess it would easiers for you to have it automated, there's so many sites with dead links, that is unbelieveble :-)

Take care and thank you!

/mike
