### ISSUE TITLE
THEME:newera

### ISSUE THREAD

**Issue by jonapaniagua** [withastro/astro.build#416]
### Theme title

newera

### Short description and preview image

Preguntando se llega a roma.

### Public repository URL

https://github.com/jonapaniagua

### Live demo URL

https://github.com/withastro/astro/tree/main/examples/basics

**Comment by tony-sull** [comment]
Hey @jonapaniagua, looks like the issue form may have lost some of your data

Can you update the issue with a preview image and links to the theme's public repo and live demo?
