### ISSUE TITLE
Add Dimension to our README sponsors

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro.build#431]
cc @suptejas from Dimension, who will send over a link to the logo asset. 

Thank you @suptejas for supporting the Astro project!

**Comment by suptejas** [comment]
Thank you so much @FredKSchott , attaching our SVG here
![dimension logo square fullcolour rgb](https://user-images.githubusercontent.com/63039748/204355904-ae761d05-8edc-4930-bea1-4b37253c0461.svg)
