### ISSUE TITLE
THEME: Astro WordPress Starter

### ISSUE THREAD

**Issue by JEverhart383** [withastro/astro.build#432]
### Theme title

Astro WordPress Starter

### Short description and preview image

A flexible starting point for people interested in using Astro with WordPress as a headless CMS using WPGraphQL.
![Screen Shot 2022-11-28 at 3 12 59 PM](https://user-images.githubusercontent.com/7818951/204371822-be2e9639-9d85-4c0d-85b4-bc4854b51321.png)

### Public repository URL

https://github.com/JEverhart383/astro-wordpress-starter

### Live demo URL

https://hnhcu867jnlofzb7xsfeuta0c.js.wpenginepowered.com/

**Comment by tony-sull** [comment]
@JEverhart383 Astro on top of headless WordPress, very cool!

The demo link isn't working for me, can you double check the URL is correct?

**Comment by JEverhart383** [comment]
@tony-sull Thanks! Looks like that was a cold start on our node server since there isn't any traffic to that site at the moment. I hung around and it eventually resolved, so the URL up there should work now and I'd be surprised to see the cold start again once it's in the wild. The threshold for the container spinning down is pretty high, but nobody's likely hit that link in a few weeks.
