### ISSUE TITLE
SHOWCASE: The Ahuja Lab - Research Lab Website

### ISSUE THREAD

**Issue by rishi-raj-jain** [withastro/astro.build#502]
Creating it here as the submit form is failing.

Website title
**The Ahuja Lab**

Short description and preview image
<img width="1512" alt="Screenshot 2023-01-14 at 10 03 24 PM" src="https://user-images.githubusercontent.com/46300090/212483616-bc6090e5-e15a-4322-bc56-7d392d7272cb.png">

Public website URL
https://ahuja-lab.in/

**Comment by tony-sull** [comment]
Added to the new list over at https://astro.build/showcase/submit 🎉 

As our showcase grew we started becoming a bottleneck keeping up with manually adding submissions to the showcase. We'll be using the new discussion to periodically update the showcase going forward and hope to automate that so it's as up-to-date as possible!
