### ISSUE TITLE
INTEGRATION: astro-bootstrap

### ISSUE THREAD

**Issue by sean-au** [withastro/astro.build#511]
### NPM package name

astro-bootstrap

### Short description (if different than package.json) and icon

Can you please update the icon to the attached file. Thanks
![64x64](https://user-images.githubusercontent.com/73884419/213944323-5e53b987-bf3d-4d78-bd30-f9c46e0e11cc.png)

### Homepage URL (if different than package.json)

n/a

**Comment by sean-au** [comment]
Just checking if someone is going to pick this issue up...

**Comment by tony-sull** [comment]
Hey @sean-au, sorry for the huge delay on this!  We were shifting around our submission flows for the new marketing site and it looks like this one slipped through the cracks!  I'll have this updated today!
