### ISSUE TITLE
THEME: AstroAgnosticUIStarter

### ISSUE THREAD

**Issue by roblevintennis** [withastro/astro.build#56]
### Theme title

AgnosticUI Starter Kit

### Short description and preview image

# AstroAgnosticUIStarter

A starter template for leveraging [AgnosticUI](https://agnosticui.com/) + [Astro](https://astro.build/) to render React, Vue 3, and Svelte. Themable via [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties).

![image](https://user-images.githubusercontent.com/142403/160436102-ea84f4cc-9c3a-4119-b0d1-f5cc73efaa6b.png)

### Public repository URL

https://github.com/AgnosticUI/AstroAgnosticUIStarter

**Comment by roblevintennis** [comment]
[sarah11918](https://github.com/sarah11918) lmk if this works 🙏

**Comment by tony-sull** [comment]
Excellent, thanks for submitting yoru theme @roblevintennis!  I hadn't seen Agnostic UI before, very cool project!  The framework-agnostic approach fits great with Astro  🚀
