### ISSUE TITLE
THEME: Simple Blog Template

### ISSUE THREAD

**Issue by pyronaur** [withastro/astro.build#60]
### Theme title

Simple Blog Template

### Short description and preview image

Lightly opinionated starter template for an Astro blog. Organized to keep markdown files separate from Astro pages.

<img width="906" alt="Screenshot 2022-03-29 at 21 31 08" src="https://user-images.githubusercontent.com/988095/160681426-a8033904-cc42-4730-800d-b8837588ae96.png">

### Public repository URL

https://github.com/OnWritingCode/simple-blog-template

### Live demo URL

https://simple-blog-template.netlify.app

**Comment by pyronaur** [comment]
I'll also appreciate any code feedback anyone might have, with things changing so quickly with Astro, I think some things may already be outdated. I haven't looked closer, but from the Astro announcement post, looks like I probably need to remove the custom Shiki setup?

**Comment by tony-sull** [comment]
Nice!  I really like the way you structured the code for loading post data, very clean :+1:

As far as Shiki goes, the main difference in `0.25` is just that Shiki is now the default

```astro
{
    syntaxHighlight: 'shiki', // doesn't hurt anything, but this is no longer needed since Shiki is the default
    shikiConfig: {
	theme: 'poimandres',
	langs: [], // I'm not 100% sure, but I think you should add "astro" here to make sure Shiki is including `.astro` formatting
	wrap: false,
    },
}
```

**Comment by pyronaur** [comment]
🥳
