### ISSUE TITLE
Flashing issues

### ISSUE THREAD

**Issue by jamesli2021** [withastro/astro.build#629]
I could notice the banner `Astro version 2.1 just shipped!` at the top of the page could "flash and disappear" despite the top banner has been closed, not obvious with a fast machine:
https://astro.build/showcase/
https://astro.build/blog/
https://astro.build/about/

Tested on macOS Ventura, Macbook M1 and latest Firefox.

**Comment by jasikpark** [comment]
maybe a cookie could do the job? https://www.netlify.com/blog/fix-cumulative-layout-shift-edge-functions/#fixing-cumulative-layout-shift-cls-with-netlify-edge-functions

**Comment by tony-sull** [comment]
This should have been handled by a `<script>` in the head, I'll take a look!

At first glance it's actually using `<script is:inline>` which may very well be the issue, pretty sure that'd put the script inlined in the `<body>` **after** the notification banner renders

**Comment by jamesli2021** [comment]
Found any fix?

**Comment by tony-sull** [comment]
Closed this last week because we weren't using the notification banner anymore

Well, turns out the banner is making a comeback!  There's a fix for this in #787 where the banner is added back in, re-opening this issue to make sure the fix is tracked properly
