### ISSUE TITLE
Skip to content button visible on mobile 

### ISSUE THREAD

**Issue by zax71** [withastro/astro.build#693]
On mobile you can view the skip to content button by scrolling up (as if to reload the page) this could be fixed by positioning it to the right or left of the page instead of on top

![IMG_0104](https://github.com/withastro/astro.build/assets/67716263/6f68e397-47fd-40e0-94ff-7c9b33d6c3cf)

**Comment by jacobthesheep** [comment]
the "Skip to content button" isn't in the new site so I think this issue can be closed.

**Comment by delucis** [comment]
The “Skip to Content” button does exist — you need to tab to it for it to appear.

I can’t reproduce this specific issue though, might need to know a specific browser @zax71.

**Comment by zax71** [comment]
That screenshot is on Firefox for IOS

**Comment by delucis** [comment]
Great to know — thank you for testing @zax71!
