### ISSUE TITLE
INTEGRATION:can you add microsoft clarity integration 

### ISSUE THREAD

**Issue by wanghaisheng** [withastro/astro.build#710]
### NPM package name

https://github.com/withastro/astro.build/blob/5c300877fcf9626c5bccb50f8f1444a465916d26/src/content/integrations/astro-google-analytics.md?plain=1#L4

### Short description (if different than package.json) and icon

https://github.com/withastro/astro.build/blob/5c300877fcf9626c5bccb50f8f1444a465916d26/src/content/integrations/astro-google-analytics.md?plain=1#L4
there is a google analytics,  I can add it to my own.but I think this user  behavior monitoring tool is really helpful

### Homepage URL (if different than package.json)

https://github.com/withastro/astro.build/blob/5c300877fcf9626c5bccb50f8f1444a465916d26/src/content/integrations/astro-google-analytics.md?plain=1#L4

**Comment by delucis** [comment]
Hi @wanghaisheng! This form is mainly for requesting we add packages that exist on npm to the website, not to create new packages that don’t currently exist.

If anyone is interested in building a Microsoft Clarity integration or Astro, I’m happy to help with any questions they might have. We have a guide to making an npm package here: https://docs.astro.build/en/reference/publish-to-npm/

**Comment by wanghaisheng** [comment]
@delucis   I have modify from the google analytic one 
https://github.com/wanghaisheng/astro-microsoft-clarity

**Comment by wanghaisheng** [comment]
@delucis 
```
(base) wenke@wenkedeMac-mini idea-to-action-cycle % pnpm config set registry http://registry.npm.taobao.org 
(base) wenke@wenkedeMac-mini idea-to-action-cycle % npm create astro@latest demo -- --template minimal      

undefined:1
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (file:///Users/wenke/.npm/_npx/abdb4b598af046c4/node_modules/create-astro/dist/index.js:284:32)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.2.0
npm ERR! code 1
npm ERR! path /Users/wenke/github/idea-to-action-cycle
npm ERR! command failed
npm ERR! command sh -c create-astro "demo" "--template" "minimal"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wenke/.npm/_logs/2023-06-12T11_10_07_312Z-debug-0.log

```

**Comment by delucis** [comment]
I see you used `pnpm` in the first command there but `npm` in the second. Should they be the same?

**Comment by wanghaisheng** [comment]
I  have tried all npm pnpm  yarn, none of them works
