### ISSUE TITLE
Extremely poor performance on Firefox Android

### ISSUE THREAD

**Issue by kanashimia** [withastro/astro.build#736]
Landing page renders at like 10fps in Firefox on Android, which is pretty funny while reading performance claims.
Issue occurs in Firefox, but not in Chromium.

I verified two devices and two different Firefox versions, one of them is the latest nightly, one is an old stable.

I think this is because of the CSS, there are a lot of "fancy" stuff going on there, perhaps it is blurs or transitions or shadows slowing things down, but that is just a guess.

Specifically those pages are very slow:
- https://astro.build/
- https://astro.build/about
- https://astro.build/themes
- https://astro.build/showcase
- https://astro.build/blog/astro-021-preview

Those are okayish, but still laggy:
- https://astro.build/blog

Those are ok:
- https://docs.astro.build/

Landing page on a desktop Firefox too feels sluggish while scrolling, although it is pretty subtle and isn't as obvious.

**Comment by delucis** [comment]
I can also confirm this. We previously narrowed this down to some mix-blend-mode issues I believe and experimented with some alternative approaches here: https://github.com/withastro/astro.build/pull/602

Not sure we were ever able to find a good solution.

**Comment by dandv** [comment]
Very poor scroll performance still present on Firefox 121 desktop on Linux. See screencast linked from #997.

**Comment by aaarichter** [comment]
@delucis this issue should be reopened - firefox scroll performance is still very bad - the fix by @tony-sull was merged almost a year ago, and I assume that it is part of the current astro.build page, but the jank is really bad. 

to be honest - this is a red flag to me when deciding between astro and alternatives.

**Comment by rosaboyle** [comment]
Still doesn't work for firefox. I don't know why you guys marked this as resolved
