### ISSUE TITLE
INTEGRATION: mr-world

### ISSUE THREAD

**Issue by jlarmstrongiv** [withastro/astro.build#753]
### NPM package name

mr-world

### Short description (if different than package.json) and icon

![mr-world](https://github.com/withastro/astro.build/assets/20903247/3291d85e-a808-4b93-96fe-8fc802dcee76)

Inspect the url to download the svg https://github.com/withastro/astro.build/assets/20903247/3291d85e-a808-4b93-96fe-8fc802dcee76

### Homepage URL (if different than package.json)

https://github.com/jlarmstrongiv/mr-world/#readme

**Comment by jacobthesheep** [comment]
Integration added, this issue can be closed.
