### ISSUE TITLE
Blank icons after a while

### ISSUE THREAD

**Issue by jetjtx** [withastro/astro.build#782]
Icons that animate from right to left under "Zero to website in whoa" appear to show glitch of blank icons unless I have reload the page, this issue has been seen quite some time.

My machine setup:
Macbook Pro M1
macOS Ventura
Firefox 116.0.3

**Comment by jetjtx** [comment]
![Screenshot 2023-08-25 at 14-00-17 Astro](https://github.com/withastro/astro.build/assets/139200988/5b74e3e1-ef29-4834-970f-2b08c86f981a)

**Comment by delucis** [comment]
Thanks for the report @jetjtx — I noticed the same behaviour myself earlier today (also running Firefox on macOS).

**Comment by julien-deramond** [comment]
If I'm not mistaken, the new homepage doesn't include this marquee anymore. And it doesn't seem to be used anywhere else for now. Maybe this issue could be closed. Except if the core team would like to keep the `<Marquee>` + `<LogoCarousel>` components, and double-check that this issue didn't come from the components themselves (which would need to be fixed).

**Comment by jetjtx** [comment]
@julien-deramond This issue has been resolved, there was a revamp in Astro home page and now it doesn't has a scrolling animation. The new design is the "exact" I have in mind!
