### ISSUE TITLE
404 pages give a browser error

### ISSUE THREAD

**Issue by zadeviggers** [withastro/astro.build#825]
On non-existent routes, e.g. astro.build/404, astro.build/broken-link, a browser encoding error is shown. Screenshots below.

Firefox:
<img width="905" alt="image" src="https://github.com/withastro/astro.build/assets/74938858/2bcb624a-a816-45e4-9a3b-03e9c9c1e5f7">
Chrome Canary:
<img width="894" alt="image" src="https://github.com/withastro/astro.build/assets/74938858/70004d35-6b74-4704-a71c-fb78a75f2424">
Safari:
<img width="682" alt="image" src="https://github.com/withastro/astro.build/assets/74938858/d3faa3a1-3736-4551-9d86-f0e961a56295">

**Comment by ascorbic** [comment]
I came to report the same thing. After digging in a bit, it looks like it's sending a `content-encoding: br` header, but the response is plain text. It even sends that header as `br` if the browser sends `accept-encoding: identity` or any other encoding.

**Comment by ElianCodes** [comment]
This should be fixed now!
