### ISSUE TITLE
Inline CSS and JavaScript

### ISSUE THREAD

**Issue by proyb6** [withastro/astro.build#827]
I've noticed on Astro site has inline JavaScript and CSS that's probably because of Vite inline them if the code is <4KB. Would it make sense not to inline for an MPA?

**Comment by delucis** [comment]
In general, inlining small amounts is OK. You lose the advantage of caching but reduce network requests, which is a reasonable trade-off. That’s why Vite sets a low threshold for what gets inlined. So I think this is fine as it is.
