### ISSUE TITLE
INTEGRATION: astro-sw

### ISSUE THREAD

**Issue by pedra** [withastro/astro.build#845]
### NPM package name

astro-sw

### Short description (if different than package.json) and icon

Please add this LOGO to Astro-sw Integration!
![handmade](https://github.com/withastro/astro.build/assets/4870358/be735f17-2b11-4e18-829b-5a82b873ccd4)

### Homepage URL (if different than package.json)

https://github.com/pedra/astro-sw#readme

**Comment by jacobthesheep** [comment]
Integration added, issue can be closed.
