### ISSUE TITLE
INTEGRATION: @qwikdev/astro

### ISSUE THREAD

**Issue by thejackshelton** [withastro/astro.build#862]
### NPM package name

@qwikdev/astro

### Short description (if different than package.json) and icon

Hey everyone! I think we are real close to an alpha stage with Qwik & Astro here, enabling **resumability**, in Astro applications.

I have added the renderer and astro-component keywords. You can find the package on npm here:
https://www.npmjs.com/package/@qwikdev/astro

I don't see a listing for this just yet, but I see that it would be updated within 24 hours, and I think it might have been around the time the first time this package was published. Here's the logo!

here's the 64x64 png!
![rsz_qwiklogo](https://github.com/withastro/astro.build/assets/104264123/6c7dc2ab-297e-4378-a7ed-244d333d07ed)

If that one doesn't turn out well on the listing please use the SVG instead 😅 

SVG
![qwik](https://github.com/withastro/astro.build/assets/104264123/98e1fd78-08de-433f-b87e-2576cf2fd535)

### Homepage URL (if different than package.json)

https://github.com/QwikDev/astro

**Comment by hamatoyogi** [comment]
Please use the latter logo, the png is the old one. 🙏🏽
