### ISSUE TITLE
Integrations with wrong url and improvement suggestions

### ISSUE THREAD

**Issue by vasfvitor** [withastro/astro.build#887]
Hello, 

There are 4 integrations from `@xexiu` that links to their website. From there, I tried their GitHub but couldn't find the integrations by the same name, after looking at the website code I see that the repo is "@xexiu/astro-components". The links could be changed to the repo or npm url. Maybe could also be renamed to something like "@xexiu/astro-components/seo"?

Amidst this, as a suggestions, there are at least 2 paid integrations that could use a "PAID" badge as same in the themes.
Another suggestion, that the link goes to a page where we can see the description/details of the integration, or its documentation, not a landing page with a "Free trial" call to action. Any better ideas?

About the "PAID" badge I understand that, if followed to the letter, will affect a bunch of other known tools that are paid but have free tiers and are widely utilized. So that's it.

If anything is to be done, I'm willing to open a PR, considering I receive direction as what to do.

Thank you.

**Comment by delucis** [comment]
Thanks for the issue @vasfvitor! We fixed the broken links in #1315.

Regarding marking integrations as “PAID”, I think this may be beyond our abilities. The catalogue pulls from the npm registry so shows packages that are available on npm, but checking the contents of a package or for specific licenses is not something the Astro team has time to do. (And of course some npm packages work with third-party services that may provide varying pricing models.)

Given that I think we can close this issue. Thanks again for the feedback!

**Comment by vasfvitor** [comment]
thank you
