### ISSUE TITLE
INTEGRATION: astro-font

### ISSUE THREAD

**Issue by rishi-raj-jain** [withastro/astro.build#925]
### NPM package name

astro-font

### Short description (if different than package.json) and icon

`astro-font` will automatically optimize your Custom Fonts, Local Fonts, Fonts over any CDN and Google fonts for performance.

### Homepage URL (if different than package.json)

https://launchfa.st/features/astro-font

**Comment by tony-sull** [comment]
#903 released with an updated homepage link and description 🚀
