### ISSUE TITLE
Image Docs - Quick Grammar Fix

### ISSUE THREAD

**Issue by light-merlin-dark** [withastro/astro.build#926]
### 📚 Subject area/topic

Images

### 📋 Page(s) affected (or suggested, for new content)

https://astro.build/blog/images/

### 📋 Description of content that is out-of-date or incorrect

Just a grammar correction for you: "for any use-case you you have in mind"

**Comment by TheOtterlord** [comment]
Thanks @light-merlin-dark! I've transfered this issue to the site repo.
