### ISSUE TITLE
Inline code and link styles collide

### ISSUE THREAD

**Issue by kevinzunigacuellar** [withastro/astro.build#955]
## Description

When there is inline code inside a link, such as:

```
[some `code`](a link)
```

the styles of the inline code and the link collide.

<img width="761" alt="image" src="https://github.com/withastro/astro.build/assets/46791833/8b85662c-86a4-4608-83ba-80dc712cd8c9">

<img width="769" alt="image" src="https://github.com/withastro/astro.build/assets/46791833/77bdcd9d-549f-4d99-bbe5-6d39f2a1fd12">

*source: [Astro blog 4.2](https://astro.build/blog/astro-420/)*

## Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by kevinzunigacuellar** [comment]
I have three possible fixes. 

- The inline code inherits the link coloring
  <img width="754" alt="image" src="https://github.com/withastro/astro.build/assets/46791833/7f56cd6c-2406-4c3c-b39a-42d74c1a073d">

- The inline code inherits the link underline styles
  <img width="760" alt="image" src="https://github.com/withastro/astro.build/assets/46791833/2422c1b8-4009-49bd-86cf-3f0f4cb29ae3">

- Solution 1 and 2 combined 💜 
  <img width="754" alt="image" src="https://github.com/withastro/astro.build/assets/46791833/d472d7d2-4616-46e8-a460-95f60e47e303">

**Comment by itsMapleLeaf** [comment]
I think 1 and 2 combined looks the best 👍

**Comment by ElianCodes** [comment]
I'm definitely in favor of adding the underline! I think the last option, with both color and underline, is the best. Feel free to open a PR!

<img width="789" alt="Screenshot 2024-01-21 at 16 23 00" src="https://github.com/withastro/astro.build/assets/15145918/c0ead044-0167-4854-a3aa-43ec51e097ae">
