### ISSUE TITLE
Add "frameworks" collection to https://astro.build/integrations/

### ISSUE THREAD

**Issue by hippotastic** [withastro/astro.build#97]
The https://astro.build/integrations/ site currently features various filters that you're calling "collections", e.g. "performance", "seo" and "analytics".

However, there does not seem to be a collection that shows all the framework integrations supported by Astro. I think this type of integration is special enough to justify its own collection.

My idea for the collection name would be "frameworks".

**Comment by readonlychild** [comment]
+1

Another one I propose is “official”

**Comment by hippotastic** [comment]
Awesome! Thanks so much for adding this! 💯
