### ISSUE TITLE
INTEGRATION: `@inlang/paraglide-js-adapter-astro`

### ISSUE THREAD

**Issue by LorisSigrist** [withastro/astro.build#990]
### NPM package name

@inlang/paraglide-js-adapter-astro

### Short description (if different than package.json) and icon

![dithered](https://github.com/withastro/astro.build/assets/43482866/fa94e751-125e-47da-93c1-dd7a8af15eeb)

### Homepage URL (if different than package.json)

https://inlang.com/c/astro

**Comment by pascal-brand38** [comment]
Hello @LorisSigrist ,

**@inlang/paraglide-js-adapter-astro** is now deprecated on npm :(

Should I update **@inlang/paraglide-astro** instead?
* with the logo
* with the homepage url https://inlang.com/c/astro? (I am not sure about this one as the current https://inlang.com/m/iljlwzfs/paraglide-astro-i18n looks better to me)

Thanks,
Pascal.

**Comment by LorisSigrist** [comment]
That would be incredibly helpful. Thank you!
